config/routes.rb
Rails.application.routes.draw do

  namespace :regional_admin do
    resources :businesses, only: [:index, :show, :destroy]
    resources :users, only: [:index, :new, :destroy, :create]
    resources :region, only: [:show, :edit, :update]
  end

  namespace :regions, as: :region, path: '/:region' do
    resources :businesses, only: [:index, :show]
  end


  namespace :regions, as: :region, path: '/:region' do
    resources :businesses, only: [:index, :show]
  end

  resources :regions,     only: [:index, :show]
  resources :portfolio,   only: [:show]
  resources :categories,  only: [:index, :show]
  resources :prospects,   only: [:index, :show, :create]
  resources :investments, only: [:show, :index, :new, :create, :update]

  post '/prospects_update', to: 'prospects#update'

  get        '/home', to: 'static_pages#home'
  get       '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'

  get '/modal_login', to: 'sessions#modal_login'

  get       '/login', to: 'sessions#new'
  post      '/login', to: 'sessions#create'
  delete   '/logout', to: 'sessions#destroy'

  resources :users

  root 'static_pages#home'

end

app/views/partials/_businesses.html.erb
<div class="container business-info">
  <div class="row">
    <% @businesses.each do |business| %>
    <div class="centered col-lg-4 col-md-4 col-sm-4">
        <div class="business">
          <p><h4><%= link_to( business.name, region_business_path(id: business.id)) %></h4></p>

          <p><%= link_to( image_tag(business.image), region_business_path(id: business.id)) %></p>

          <p>Funding needed:</p>
          <p><%= number_to_currency(business.funding_needed / 100) %></p>
          <p>Funding Raised:</p>
          <p><%= number_to_currency(business.funding_to_date / 100) %></p>
          <p><%= link_to "Learn More", region_business_path(id: business.id) %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_default_nav.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to "Regions", regions_path %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to "Prospects (#{load_prospects.count_them})", prospects_path, class: "navbutton" %>
  </li>
  <li class="dropdown">
    <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <% if current_user.nil? %>
        <li>
          <a href="#" data-toggle="modal" data-target="#modal-login">Login</a>
        </li>
        <li>
          <%= link_to "Create Account", new_user_path, class: "navbutton" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Logout", logout_path, method: "delete"%>
        </li>
        <li>
          <%= link_to "My Account", user_path(current_user), class: "navbutton" if current_user %>
        </li>
        <li>
          <%= link_to "My Investments", investments_path %> 
        </li>
      <% end  %>
    </ul>
  </li>
</ul>

app/views/partials/_lend.html.erb
<div class="element">
<%= form_for(:prospect, url: :prospects) do |f| %>
  <%= f.hidden_field :business_id, value: @business.id %>
  <p><%= f.text_field :amount %>
  <%= f.submit "Lend"%></p>
<% end %>
</div>

app/views/partials/_modal_login.html.erb
<!-- Login Modal -->
<div class="modal fade" id="modal-login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:session, url: :login) do |f| %>
          <%= f.text_field :email, placeholder: 'email address', class: 'login-text' %><br>
          <%= f.password_field :password, placeholder: 'password', class: 'login-text' %><br>
      <div class="modal-footer">
          <%= f.submit 'Login', class: 'btn btn-success' %>
        <% end %><br>
        
        <a href="#" id="create-modal-link" data-toggle="modal" data-target="#modal-create-user">No account? Create one now!</a>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="logo" href="/"><%= image_tag("lendio-small.png")%></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if regional_admin? %>
        <%= render partial: 'partials/regional_admin_nav' %>
      <% elsif platform_admin? %>
        <%= render partial: 'partials/platform_admin_nav' %>
      <% else %>
        <%= render partial: 'partials/default_nav' %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_new_regional_admin_modal.html.erb
<!-- Login Modal -->
<div class="modal fade" id="modal-create-regional-admin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create Regional Admin</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:user, url: :regional_admin_users) do |f| %>
          <%= f.text_field :first_name, placeholder: 'first name', class: 'login-text' %><br>
          <%= f.text_field :last_name, placeholder: 'last name', class: 'login-text' %><br>
          <%= f.text_field :username, placeholder: 'username', class: 'login-text' %><br>
          <%= f.text_field :email, placeholder: 'email address', class: 'login-text' %><br>
          <%= f.password_field :password, placeholder: 'password', class: 'login-text' %><br>
          <%= f.password_field :password_confirmation, placeholder: 'confirm password', class: 'login-text' %><br>
      <div class="modal-footer">
          <%= f.submit 'Create Account', class: 'btn btn-success' %>
        <% end %><br>
      </div>
    </div>
  </div>
</div>

app/views/partials/_new_user_fields.html.erb
<%= f.text_field :first_name, placeholder: "first name", class: "form-control" %>
<%= f.text_field :last_name, placeholder: "last name", class: "form-control"  %>
<%= f.text_field :username, placeholder: "username", class: "form-control"  %>
<%= f.text_field :email, placeholder: "email address", class: "form-control"  %>
<%= f.password_field :password, placeholder: "password", class: "form-control"  %>
<%= f.password_field :password_confirmation, placeholder: "confirm password", class: "form-control" %><br /><br />

app/views/partials/_new_user_modal.html.erb
<!-- Login Modal -->
<div class="modal fade" id="modal-create-user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create User</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:user, url: :users) do |f| %>
          <%= f.text_field :first_name, placeholder: 'first name', class: 'login-text' %><br>
          <%= f.text_field :last_name, placeholder: 'last name', class: 'login-text' %><br>
          <%= f.text_field :username, placeholder: 'username', class: 'login-text' %><br>
          <%= f.text_field :email, placeholder: 'email address', class: 'login-text' %><br>
          <%= f.password_field :password, placeholder: 'password', class: 'login-text' %><br>
          <%= f.password_field :password_confirmation, placeholder: 'confirm password', class: 'login-text' %><br>
      <div class="modal-footer">
          <%= f.submit 'Create Account', class: 'btn btn-success' %>
        <% end %><br>
      </div>
    </div>
  </div>
</div>

app/views/partials/_notices.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/partials/_platform_admin_nav.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage Region<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "Logout", logout_path, method: "delete"%>
      </li>
      <li>
        <%= link_to "My Account", user_path(current_user), class: "navbutton" if current_user %>
      </li>
      <li>
        <%= link_to "Administrators", root_path %>
      </li>
      <li>
        <%= link_to "Regions", root_path %>
      </li>
    </ul>
  </li>
</ul>

app/views/partials/_promoted.html.erb
<div class="container business-info">
  <div class="row">
    <% @businesses.each do |business| %>
    <div class="centered col-lg-4 col-md-4 col-sm-4">
        <div class="business">
          <p><h4><%= business.name %></h4></p>
          <p><%= link_to( image_tag(business.image), region_business_path(region: business.region_id, id: business.id)) %></p>

          <p>Funding needed:</p>
          <p><%= number_to_currency(business.funding_needed / 100) %></p>
          <p>Funding to date:</p>
          <p><%= number_to_currency(business.funding_to_date / 100) %></p>
          <p><%= link_to "Learn More", region_business_path(region: business.region_id, id: business.id) %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_regional_admin_modal.html.erb
<!-- Login Modal -->
<div class="modal fade" id="modal-admin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Admin by Email</h4>
      </div>
      <div class="modal-body">
        <%= form_tag (regional_admin_make_admin_path) do %>
          <%= text_field_tag 'email' %><br><br>
         <div class="modal-footer">
          <%= submit_tag "Make Admin", class: "btn btn-success" %>
        <% end %>
          </div>
        <a href="#" id="create-modal-link" data-toggle="modal" data-target="#modal-create-regional-admin">No account? Create new admin now!</a>
      </div>
    </div>
  </div>
</div>

app/views/partials/_regional_admin_nav.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage Region<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "Logout", logout_path, method: "delete"%>
      </li>
      <li>
        <%= link_to "My Account", user_path(current_user), class: "navbutton" if current_user %>
      </li>
       <li>
        <%= link_to "Region Information", regional_admin_region_path(id: current_user.region_id) %>
      </li>
      <li>
        <%= link_to "Administrators", regional_admin_users_path %>
      </li>
      <li>
        <%= link_to "Businesses", regional_admin_businesses_path %>
      </li>
    </ul>
  </li>
</ul>

app/views/partials/_regions.html.erb
<h2>Regions</h2>
<div class="container business-info">
  <div class="row">
    <% @regions.each do |region| %>
    <div class="centered col-lg-4 col-md-4 col-sm-4">
        <div class="region">
          <p><h3><%= link_to region.name, region_businesses_path(region) %></h3></p>
          <p><%= link_to(image_tag(region.image_file_name), region_businesses_path(region)) %></p>
          <p>Number of businesses: <%= business_count(region) %></p>
          <p><%= region.description %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>