config/routes.rb
Rails.application.routes.draw do

  namespace :regional_admin do
    resources :businesses, only: [:index, :show, :destroy]
    resources :users, only: [:index, :new, :destroy, :create]
    resources :region, only: [:show, :edit, :update]
  end

  namespace :regions, as: :region, path: '/:region' do
    resources :businesses, only: [:index, :show]
  end


  namespace :regions, as: :region, path: '/:region' do
    resources :businesses, only: [:index, :show]
  end

  resources :regions,     only: [:index, :show]
  resources :portfolio,   only: [:show]
  resources :categories,  only: [:index, :show]
  resources :prospects,   only: [:index, :show, :create]
  resources :investments, only: [:show, :index, :new, :create, :update]

  post '/prospects_update', to: 'prospects#update'

  get        '/home', to: 'static_pages#home'
  get       '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'

  get '/modal_login', to: 'sessions#modal_login'

  get       '/login', to: 'sessions#new'
  post      '/login', to: 'sessions#create'
  delete   '/logout', to: 'sessions#destroy'

  resources :users

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to  :region
  has_many    :investments

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, email: true, uniqueness: true
  validates :password, presence: true,
                       :confirmation => true,
                       :length => { :within => 6..40 },
                       :unless => :already_has_password?
  validates_length_of :username, :maximum=>32, :minimum=>2

  has_secure_password

  enum role: ['default', 'regional-admin', 'platform-admin']

  def to_param
    email
  end

  def regional_admin?
    role == 'regional-admin'
  end

  def platform_admin?
    role == 'platform-admin'
  end

  def investments_detail
    investments.map do |investment|
      investment.details
    end
  end

  def self.regional_managers(region_id)
    where(region_id: region_id).where(role: 1)
  end

  def self.make_default(id)
    find(id).update(region_id: nil, role: 0)
  end

  private

  def already_has_password?
    !self.password_digest.blank?
  end

end

app/controllers/admin/regional/users_controller.rb
class Admin::Regional::UsersController < Admin::Regional::BaseController

  def index
    @admins = User.regional_managers(current_user.region_id)
  end

  def new
  end

  def create
    user = User.new(admin_params)
    if user.save
      user.update(region_id: current_user.region_id, role: 1)
      redirect_to admin_regional_users_path
    else
      flash[:notice] = "Invalid attributes, new admin not created."
      redirect_to admin_regional_users_path
    end
  end

  def destroy
    User.make_default(params[:id])
    redirect_to admin_regional_users_path
  end

  private

  def admin_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

end

app/controllers/regional_admin/users_controller.rb
class RegionalAdmin::UsersController < RegionalAdmin::BaseController

  def index
    @admins = User.regional_managers(current_user.region_id)
  end

  def new
  end

  def create
    user = User.new(admin_params)
    if user.save
      user.update(region_id: current_user.region_id, role: 1)
      redirect_to regional_admin_users_path
    else
      flash[:notice] = "Invalid attributes, new admin not created."
      redirect_to regional_admin_users_path
    end
  end

  def destroy
    User.make_default(params[:id])
    redirect_to regional_admin_users_path
  end

  private

  def admin_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserNotifier.send_signup_email(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "Invalid fields"
      render :new
    end
  end

  def show
  end

  def cart
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(email: params[:user][:email])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:notice] = "Invalid fields"
      render :edit
    end
  end

  private

  def logged_in_user
    unless logged_in?
      redirect_to login_path
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

end

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name, value: @user.first_name %><br /><br />
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name, value: @user.last_name%><br /><br />
  <%= f.hidden_field :username, value: @user.username %>
  <%= f.label :email %><br />
  <%= f.text_field :email, value: @user.email %><br /><br />
  <%= f.label :password %><br />
  <%= f.password_field :password, value: @user.password %><br /><br />
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, value: @user.password %><br /><br />
  <%= f.submit "Update Account", class: 'btn btn-success' %>
<% end %>

app/views/users/new.html.erb
<form class="new-user">
  <div class="form-group">
    <div class="container">
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
          <%= form_for(@user) do |f| %>

            <%= render partial: 'partials/new_user_fields', locals: { f: f } %>

            <%= f.submit "Create Account", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>  
  </div>  
</form>

app/views/users/show.html.erb
<br>
<div class = "welcome">
<h2>Welcome, <%= current_user.first_name %>!</h2>
</div>
<p>First Name: <%= current_user.first_name %></p>
<p>Last Name: <%= current_user.last_name %></p>
<p>Email:  <%= current_user.email %></p>
<p>Password: •••••••• </p>
<%= @previous_order %>
<br />
<%= link_to "Edit Profile", edit_user_path(id: current_user.id), class:'btn' %>