config/routes.rb
Rails.application.routes.draw do

  namespace :regional_admin do
    resources :businesses, only: [:index, :show, :destroy]
    resources :users, only: [:index, :new, :destroy, :create]
    resources :region, only: [:show, :edit, :update]
  end

  namespace :regions, as: :region, path: '/:region' do
    resources :businesses, only: [:index, :show]
  end


  namespace :regions, as: :region, path: '/:region' do
    resources :businesses, only: [:index, :show]
  end

  resources :regions,     only: [:index, :show]
  resources :portfolio,   only: [:show]
  resources :categories,  only: [:index, :show]
  resources :prospects,   only: [:index, :show, :create]
  resources :investments, only: [:show, :index, :new, :create, :update]

  post '/prospects_update', to: 'prospects#update'

  get        '/home', to: 'static_pages#home'
  get       '/about', to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'

  get '/modal_login', to: 'sessions#modal_login'

  get       '/login', to: 'sessions#new'
  post      '/login', to: 'sessions#create'
  delete   '/logout', to: 'sessions#destroy'

  resources :users

  root 'static_pages#home'

end

app/controllers/regional_admin/base_controller.rb
class RegionalAdmin::BaseController < ApplicationController

end

app/controllers/regional_admin/businesses_controller.rb
class RegionalAdmin::BusinessesController < RegionalAdmin::BaseController

  def index
    @businesses = Business.where(region_id: current_user.region_id)
  end

  def show
  end

  def edit

  end

  def update
  end

  def create
  end

  def destroy
    business = Business.where(region_id: current_user.region_id).find(params[:id])
    if business.destroy
      redirect_to regional_admin_businesses_path, success: "Business has been deleted."
    else
      messages = business.errors.full_messages.join(', ')
      redirect_to regional_admin_businesses_path, danger: messages
    end
  end

  private

  def business_params

  end

end

app/controllers/regional_admin/region_businesses_controller.rb
class RegionalAdmin::RegionBusinessesController < RegionalAdmin::BaseController

  def index
    @businesses = Business.where(region_id: current_user.region_id)
  end

  def show
  end

  def edit
  end

  def update
  end

  def create
  end

  def destroy
    business = Business.where(region_id: current_user.region_id).find(params[:id])
    if business.destroy
      redirect_to regional_admin_region_businesses_path, success: "Business has been deleted."
    else
      messages = business.errors.full_messages.join(', ')
      redirect_to regional_admin_region_businesses_path, danger: messages
    end
  end

  private

  def business_params

  end

end

app/controllers/regional_admin/region_controller.rb
class RegionalAdmin::RegionController < RegionalAdmin::BaseController

  def show
    @region = Region.find(current_user.region_id)
  end

  def edit
    @region = Region.find(current_user.region_id)
  end

  def update
    region = Region.find(current_user.region_id)
    if region.update(region_params)
      redirect_to regional_admin_region_path(region), success: "Region data successfully updated"
    else
      redirect_to edit_regional_admin_region_path(region), danger: region.errors.full_messages.join(', ')
    end
  end

  private

  def region_params
    params.require(:region).permit(:image, :name, :description)
  end

end

app/controllers/regional_admin/users_controller.rb
class RegionalAdmin::UsersController < RegionalAdmin::BaseController

  def index
    @admins = User.regional_managers(current_user.region_id)
  end

  def new
  end

  def create
    user = User.new(admin_params)
    if user.save
      user.update(region_id: current_user.region_id, role: 1)
      redirect_to regional_admin_users_path
    else
      flash[:notice] = "Invalid attributes, new admin not created."
      redirect_to regional_admin_users_path
    end
  end

  def destroy
    User.make_default(params[:id])
    redirect_to regional_admin_users_path
  end

  private

  def admin_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end

end

app/controllers/regions/businesses_controller.rb
class Regions::BusinessesController < Regions::BaseController

  def index
    @region = Region.find(params[:region])
    @businesses = Business.where(region_id: @region.id)
  end

  def show
    @business = Business.find(params[:id])
  end

end

app/views/regional_admin/businesses/edit.html.erb
<div class="container business-info">
        <div class="individual_business">
          <div class="col-xs-12">
            <div class="region-form edit-form">
      <h2>Edit Business</h2>

        <%= form_for(:business, url: :regional_admin_business, html: {multipart: true}, method: :put) do |f|%>
          <p><%= image_tag(@business.image) %></p>
          <p><%= f.label :name %></p>
          <div class='element'><p><%= f.text_field :name, value: @business.name %></p></div>
          <p><%= f.label :description %></p>
          <div class='element'><p color:'black'><%= f.text_area :description, value: @business.description %></p></div>
          <p><%= f.label :funding_needed %></p>
          <div class='element'><p color:'black'><%= f.text_field :funding_needed, value: number_to_currency(@business.funding_needed), class: "lend-box" %></p></div>
          <p><%= f.label :funding_to_date %></p>
          <div class='element'><p color:'black'><%= f.text_field :funding_to_date, value: number_to_currency(@business.funding_to_date), class: "lend-box" %></p></div>
          <p><%= f.file_field :image, class: 'file-field'%></p>
      <p><%= f.submit "Update", class: "btn btn-success" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/regional_admin/businesses/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-6 col-md-offset-3 text-center'>
      <h3>Regional Businesses</h3>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-6 col-md-offset-3 text-center'>
      <table class='table'>
        <tr>
          <td><strong>Name</strong></td>
          <td><strong>Funding Needed</strong></td>
          <td><strong>Funding To Date</strong></td>
          <td><strong>Edit Information</strong></td>
          <td><strong>Delete Business</strong></td>
        </tr>
        <% @businesses.each do |business| %>
        <tr>
          <div class='prospect'>
            <td>
              <p><%= business.name %></p>
            </td>
            <td>
              <p><%= number_to_currency(business.funding_needed/100) %></p>
            </td>
            <td>
              <p><%= number_to_currency(business.funding_to_date/100) %></p>
            </td>
            <td>
              <%= button_to "Edit", root_path, class: 'btn btn-success', method: :get %>
            </td>
            <td>
              <%= button_to "Delete", regional_admin_business_path(id: business.id), class: 'btn btn-success', method: :delete %>
            </td>
          </div>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/regional_admin/businesses/show.html.erb
<h1>SHOW PAGE!!</h1>